### ISSUE TITLE
Will this patch work after 10/31/2024? (See Neat's threat in description.)

### ISSUE THREAD

**Issue by greatzot** [kevingigiano/neat-legacy#16]
First of all, thanks for making this patch. This is not really an issue but I don't see another way to comment so I'm just putting it here.

I tried installing on a virtual machine (Win7 64 pro in VirtualBox, on a Win10 host machine) to see what would happen. Overall it seemed to work, though I had to enable internet access temporarily to download whatever Neat needs to install itself (.Net 4.5.1 and some other stuff I'm not sure about). I didn't apply the patch before attempting to start once to see what would happen, but then I closed and applied the patch. After that, I got some weird prompt saying one or two of the files I was attempting to overwrite with the patch were in use. I tried to track down any Neat stuff running in the background but didn't see any, and in spite of the prompt, when I started Neat again, the patch had done its job. So not sure what triggered that prompt--presumably the necessary files were indeed overwritten in spite of the prompt saying it couldn't overwrite them.

But the thing about having to go fetch some stuff during the install makes me wonder if the recently emailed threat from Neat below is going to cause issues after October 31--i.e., will it even be possible to install, regardless of whether you can continue to use an existing install?

Here is Neat's thinly veiled threat, which normal people would call something like "extortion", but Neat calls "helping customers":

"As you are aware, Neat stopped supporting our offline, legacy software over 5 years ago. However, it has come to our attention that there are still some customers who continue to use our legacy products. As Windows and Mac continue to update their operating systems, the legacy Neat software is increasingly at risk of no longer functioning, making the locally stored database (and any locally stored backups) permanently inaccessible and unrecoverable. Some of our customers have already experienced this based on their specific operating system and Neat version they were using, and we would like to help our customers avoid this situation in the future.  To prevent this from happening to more Neat Legacy Software users in the future, we intend on disabling the legacy software effective 10/31/2024."

Any ideas on this? Will this patch continue to be useful for an install after that date? Seems like it should address Neat trying to disable an existing install after October 31--though please correct me if my assumption is wrong--but it's not clear to me if the program only tries to call home to Neat after installation, or if there's something going on during the installation that could let them actually prevent new installs after Oct. 31. Nor do I know what other framework/third-party/whatever-you-call-it type stuff besides .Net 4.5.1 needs to be installed to theoretically make a totally offline install possible.

**Comment by kevingigiano** [comment]
Glad you got it working.

Not sure what your original hickup was?
I have found that rebooting after install of Neat is unavoidable.

I never bothered to see if further calls were made to Neat after startup.
There may be other calls that I missed that didn't actually cause the software to crash and burn.
The only way to know for sure would be to snif traffic on you network using Wireshark or something similar.

I highly doubt they would try to sabatoge someone using their legacy products but anything is possible.
Since you are running VirtualBox, you could take a snapshot of your VM as a back up before 10/31.
An easy way to completely avoid being fubared by Neat would be to disable the Nics on your VM.

> To prevent this from happening to more Neat Legacy Software users in the future, we intend on disabling the legacy software effective 10/31/2024

I think the threat here is they will stop allowing anyone with a valid subscription to connect to Neat anymore with older versions of their software?
Effectively bricking _legacy_ versions of their software.


What I did is hack the existing software to remove chunks of code that make calls to Neat at startup.
This may result in undesired or unknown behavior, so obviosly no promisses on how long this will work.
I have consided building an open source replacement for the existing Neat software, but I am super busy and I am not sure their is a huge desire for the undertaking.
